### ISSUE TITLE
default lower the mem-clock

### ISSUE THREAD

**Issue by krtschmr** [Cyclenerd/ethereum_nvidia_miner#1]
https://github.com/Cyclenerd/ethereum_nvidia_miner/blob/master/files/nvidia-overclock.sh#L11

starting with 600 is a little bit aggressive as it can freeze systems before they even really started (that's a common issue with afterburner+win: people put +800 or something into the mem and as a startup + default loading. so the PC freezes, reboots and freezes again)

**Comment by s1eight** [comment]
Keep in mind these are offset values for Nvidia LINUX. 600 is not high at all as an offset. Nvidia works differently in linux than MSI afterburner in windows. I have my offset at 1200 memory transfer rate, no crashes at all.

**Comment by lngarrett** [comment]
Agreed, 600 is about as high as I could go on Windows. I use 1200 on Linux.

**Comment by krtschmr** [comment]
@s1eight means 600 isn't the *added* speed but just the total?

okay 👍

**Comment by krtschmr** [comment]
@lngarrett so 1200 clockrate total?

**Comment by lngarrett** [comment]
@krtschmr 

GPUMemoryTransferRateOffset=1200 on my rig. 1500 was unstable.

**Comment by krtschmr** [comment]
@lngarrett which cards exactly? offset 1200 means +1200 above default (whatever it is) or 1200 total (sounds slow)

**Comment by Cyclenerd** [comment]
Btw. `nvidia-overclock.sh`is not in autostart.

**Comment by lngarrett** [comment]
@krtschmr GTX 1070

**Comment by krtschmr** [comment]
@lngarrett  that's a good question. with +1200 it would explode. if it's half steps 0.5 each, then it's +600, should be likely maximum i guess.

**Comment by Cyclenerd** [comment]
I close this issue. `nvidia-overclock.sh` is not in autostart. Note added. Change in small steps.
