### ISSUE TITLE
Issue with nvidia-overclock.sh settings.

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#10]
ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
       specified in assignment '[gpu:{0..5}]/GPUPowerMizerMode=1'.

ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
       specified in assignment '[gpu:{0..5}]/GPUFanControlState=1'.

ERROR: Error resolving target specification 'fan:{0..5}' (No targets match target specification),
       specified in assignment '[fan:{0..5}]/GPUTargetFanSpeed=75'.

ERROR: Error parsing assignment '[gpu:{0..5}]/GPUGraphicsClockOffset[3]==100' (No attribute value
       specified).

ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
       specified in assignment '[gpu:{0..5}]/GPUMemoryTransferRateOffset[3]=600'.

**Comment by Yive** [comment]
I had that happen too, just means that those cards don't exist, nothing to really worry about.

**Comment by Kainzo** [comment]
@Yive  from Spigot Mirrors? :D bro!

**Comment by Cyclenerd** [comment]
I could hide the errors message. But I did not want to. Maybe someone is wondering if the message does not  appear. Just change the number of your cards in the script.

**Comment by Kainzo** [comment]
Change the number of cards in what script? @Cyclenerd

**Comment by jimmykl** [comment]
@Kainzo In your nvidia-overclock.sh script on line 18 where it says:

```for MY_DEVICE in {0..5}```

Change 5 to however many cards you have minus one (because the first card is 0) and save it.

Then run the script and it will only loop through those settings for the number of cards you have and you won't get any 'errors' when the script tries to set settings on cards which do not exist.

But it doesn't hurt to leave it as is either.

**Comment by Kainzo** [comment]
I actually did change it to "6" from 5... and it still gave the errors... is there a way to wipe the slate clean?

**Comment by Kainzo** [comment]
When I changed it to the appropriate cards, how do I check to make sure the overclocks worked?

**Comment by Cyclenerd** [comment]
See `gpu` console.

**Comment by Cyclenerd** [comment]
Something else: In another ticket I see you're using `sh`. Please follow the instructions and use `bash`, then you will also have fewer questions.

**Comment by Kainzo** [comment]
I attempted bash first, didn't work.  This is still an issue and I'm unsure why - is there a way to wipe settings completely and start over?

**Comment by Cyclenerd** [comment]
copy image to usb flash drive

**Comment by Kainzo** [comment]
Thanks much! I'll give it a go.
