### ISSUE TITLE
Low Hash Rate Comparatively.

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#11]
So just coming from a fresh Win10 x64 install, I have 150/mhs using claymore miner.  
Using the same overclock setting and etc I am only getting 140-143/mhs.

Is there any reason for this difference? any settings maybe I missed? is Ubuntu truly going to be lower hash?

Hoping to get back my 7 hash so I can rock it out on this new distro!

**Comment by Cyclenerd** [comment]
In the `miner.sh`, the developer fee is deactivated. Please note that...

**Comment by andreasd** [comment]
i just tested the claymore miner with both nofee=1 and nofee=0 (=paying fee). for me, the fee (and the optimizations) are worth it. i get about 4-4.5% higher Mh/s with the fee, which is 2.5%. So it's still faster.

i'm planning to clean up my copy of the miner.sh a bit more, than might send you a pull request for it. i've added dual mining variables for the claymore miner and moved a buch of other stuff into variables to make it easier to maintain. 

on another note: might be worth making a central "config.txt" file that holds all the variables, so they won't get overwritten by the update script.

**Comment by Cyclenerd** [comment]
Good to hear. I wanted to have this separated. Mining and Overclocking. Run `update.sh` after the installation and before the adjustment. Then your miner works and you do not change anything anymore... It is quite wanted that all script also `miner.sh` be customized by the user. Everyone has other miners. For example, not equal cards in a rig.

**Comment by Kainzo** [comment]
I have the dev fee on, its still 5-7 hash lower across the board using Ubuntu vs Win10.

I'm really unsure why this is happening and maybe its a driver issue? The ubuntu drivers are 381 and the Win10 is 382+

**Comment by Yive** [comment]
I have noticed that my 1060 6GB went down to ~18MH/s vs the 23MH/s I had on windows. Personally I don't really care since my 780 went from 2MH/s to 14MH/s so I suppose it's worth the loss of speed with the 1060.

**Comment by andreasd** [comment]
@Kainzo did you also adjust the power target settings according to your cpu? afaik its set to 70 in the scripts, which is quite low for e.g. 1070s.

in general: i would not just copy the overclock settings from windows. run the miner in one window and test out the overclock settings/power usage in another - make notes of the Mh/s and then decide what to use. i have different settings with the same card on win and linux.

**Comment by ObscenityIB** [comment]
no idea why you guys are getting so low, im getting around 980MH/s average...

whats up with that? o3o

**Comment by rdasx** [comment]
Check the power limit in the miner script (nvidia-smi -pl ##)

Also keep in mind that the memory transfer rate offset is in 1/2 steps, at
least on my 1050ti. Apply twice the over clock you used on Windows. I don't
know if the same is true for the graphics clock

**Comment by andreasd** [comment]
@ObscenityIB 980Mh/s with ethminer on a nvidia gpu?

**Comment by michaelphenderson** [comment]
Using my own power script and they are at 151 right now I usually set at 110 when all is stable

**Comment by Kainzo** [comment]
Power limit is set exactly the same as Windows 10.    I am getting 1-2 less hash per machine due to this.  

The Windows 10 rig has 70% consumption (120w > 70% > 85 watt) its 85watt on Ubuntu.
The overclock settings are exactly the same.

Twice the overclock would be 1200 instead of 600? am I reading this right, @rdasx?
I'm running Zotac 1060 6gb blower editions

**Comment by rdasx** [comment]
Correct. My limited research shows the Windows overclocking tools show the memory clock in DDR (GDDR3) effective rates (actual clock x 2) while the nvidia-settings on linux shows the QDR (GDDR5) effective rates (actual clock x 4). This is why we need to double the windows settings on linux.

**Comment by Kainzo** [comment]
Thanks @rdasx... so I've put +600 on Win10... ill try for +1200 on Ubuntu :)

**Comment by Cyclenerd** [comment]
I close this issue. With the same software (version etc.) and the same clock, equal values should come out. Tested by myself and many users.

**Comment by Kainzo** [comment]
So I was able to remedy this by using +1200... however system stability is a big issue now.

1060 6GBs start at 18.5 mhs, when I apply overclocks they jump to 22.5 mhs but then fall to 13 mhs.
I don't know if this is a cause in Ubuntu or maybe the clocks.  Wattage is default at 75W.
