### ISSUE TITLE
Embedded build

### ISSUE THREAD

**Issue by IamCarbonMan** [Cyclenerd/ethereum_nvidia_miner#12]
Not sure that this is entirely within the scope you're going for, but it would be really nice to see a dedicated mining image. This would be essentially an embedded system aimed at getting the most performance out of the miner. You would probably want to start with something extremely lightweight like Alpine Linux or Minimal Linux Live, and among other things, be sure to compile the mining executables statically.

**Comment by Cyclenerd** [comment]
This also makes this image. It is only for mining.

**Comment by IamCarbonMan** [comment]
....No, no it's not. It's an entire Ubuntu server. The point is that you most certainly don't need an entire Ubuntu server to run a single executable, and you'll get much better performance and insanely much smaller disk space using an embedded Linux variant, the kind of Linux distribution intended to create single-application images. Just because you take a general-purpose Linux distribution and the only thing you install on it is a miner, does not mean that it has ceased to be a general-purpose Linux distribution.

**Comment by Cyclenerd** [comment]
You also need the NVIDIA driver an X server. A few GNU tools also help. In principle I am also a big fan of Arch. But I find Ubuntu here is easy. NVIDIA supports this perfectly and I believe most of the performance comes from CUDA and the miner.

**Comment by IamCarbonMan** [comment]
I'll probably work on a fork. All you really need here is a kernel with nvidia support, busybox or coreutils and an init program to spawn the (statically built) miner. Not sure if the X server is absolutely necessary, but if it is you could always use xvfb, which is orders of magnitude lighter than the standard X server.

Performance gains from anything like this would be negligible. But in general, the fewer components the better. Here you only need a few components (as opposed to a whole distro) since you're really only doing one thing. Honestly, if you throw this together as a live USB anybody can carry it around in their pocket, stick it in a computer with an NVIDIA card, and make some ETH.

**Comment by Cyclenerd** [comment]
NVIDIA X Server is really necessary. Otherwise no overclocking with `nvidia-settings`. I close thie issue.
