### ISSUE TITLE
overclocking not working

### ISSUE THREAD

**Issue by cdubbm** [Cyclenerd/ethereum_nvidia_miner#14]
Overclocking does not seem to work at all....

miner18 ~ $ bash nvidia-overclock.sh
<SNIP>
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
<SNIP>
Done

miner18 ~ $

**Comment by Cyclenerd** [comment]
What is the `nvidia-smi` output?

**Comment by cdubbm** [comment]
See below....

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
| 31%   46C    P8     7W / 151W |     20MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    Off  | 0000:02:00.0      On |                  N/A |
| 31%   47C    P8     6W / 151W |      9MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1070    Off  | 0000:05:00.0      On |                  N/A |
| 29%   43C    P8     6W / 151W |      9MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1070    Off  | 0000:06:00.0      On |                  N/A |
| 30%   45C    P8     6W / 151W |      9MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 1070    Off  | 0000:07:00.0      On |                  N/A |
| 32%   47C    P8     7W / 151W |      9MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 1070    Off  | 0000:08:00.0      On |                  N/A |
| 29%   43C    P8     6W / 151W |      9MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3856    G   /usr/lib/xorg/Xorg                              18MiB |
|    1      3856    G   /usr/lib/xorg/Xorg                               7MiB |
|    2      3856    G   /usr/lib/xorg/Xorg                               7MiB |
|    3      3856    G   /usr/lib/xorg/Xorg                               7MiB |
|    4      3856    G   /usr/lib/xorg/Xorg                               7MiB |
|    5      3856    G   /usr/lib/xorg/Xorg                               7MiB |
+-----------------------------------------------------------------------------+

**Comment by Cyclenerd** [comment]
Please run `miner.sh`to enable Persistence-Mode and try again.

**Comment by cdubbm** [comment]
Enabled persistence mode for GPU 0000:01:00.0.
Enabled persistence mode for GPU 0000:02:00.0.
Enabled persistence mode for GPU 0000:05:00.0.
Enabled persistence mode for GPU 0000:06:00.0.
Enabled persistence mode for GPU 0000:07:00.0.
Enabled persistence mode for GPU 0000:08:00.0.
All done.

same thing afterwards, no change.

**Comment by Cyclenerd** [comment]
How is your `xorg.conf`? Did you make a `reboot` after` nvidia-config.sh`?

**Comment by cdubbm** [comment]
xorg conf looks perfectly normal. rebooted many many times now after having done it :)

**Comment by Cyclenerd** [comment]
Does it work now?

**Comment by cdubbm** [comment]
no - same exact error message.

**Comment by Cyclenerd** [comment]
Can you run `x11vnc` and connect via VNC? Have you made the settings on your mainboard? Display 0 must be an NVIDIA card! Does `nvidia-setting` works via VNC?

**Comment by cdubbm** [comment]
how do i get display 0 to be nvidia? this may be my issue....

**Comment by Cyclenerd** [comment]
I.e. disable intern grafic card.

**Comment by michaelphenderson** [comment]
This, z170a's I have freak out nvidia drivers, nomodeset my help

**Comment by Kainzo** [comment]
I dont think you need to disable the integrated... I've done it without having to do this.

**Comment by Cyclenerd** [comment]
I close this issue. Display 0 must be an NVIDIA card as described in the manual. The output must therefore be adapted in the BIOS settings if necessary. Check for security and disable internal graphics.
