### ISSUE TITLE
Unable to Determine number of GPUs 

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#16]
```
prospector@mine ~ $ sh nvidia-config.sh
Using X configuration file: "/etc/X11/xorg.conf".
WARNING: Unable to use the nvidia-cfg library to query NVIDIA hardware.
ERROR: Unable to determine number of GPUs in system; cannot honor '--enable-all-gpus' option.
```

Backed up file '/etc/X11/xorg.conf' as '/etc/X11/xorg.conf.backup'
New X configuration file written to '/etc/X11/xorg.conf'

**Comment by Cyclenerd** [comment]
Just to be sure... What if you do not use `sh`, but `bash` as written in the tutorial? Are the cards recognized by Kernel?

**Comment by Kainzo** [comment]
sh and bash are the same.  I've been running Linux for over a decade.  That makes no difference.

**Comment by Kainzo** [comment]
I tried it with bash as well... there really shouldnt be any difference between the two based on the scripts.

> prospector@mine ~ $ bash nvidia-config.sh
> 
> Using X configuration file: "/etc/X11/xorg.conf".
> 
> WARNING: Unable to use the nvidia-cfg library to query NVIDIA hardware.
> 
> 
> ERROR: Unable to determine number of GPUs in system; cannot honor '--enable-all-gpus' option.
> 
> Backed up file '/etc/X11/xorg.conf' as '/etc/X11/xorg.conf.backup'
> New X configuration file written to '/etc/X11/xorg.conf'
> 
> 
> Done

**Comment by Cyclenerd** [comment]
I'm not sure what you did. Based on the amount of questions you have, I would just restart and follow exactly the instructions.
