### ISSUE TITLE
How to reduce storage footprint?

### ISSUE THREAD

**Issue by jimmykl** [Cyclenerd/ethereum_nvidia_miner#18]
Is the full 24GB of data on the img required? How would I go about removing any unnecessary features to reduce the install size? I have some 16GB USB sticks I would like to use to run my rigs.

Sorry this isn't really an issue but I'm not sure where to put 'feature' requests.

**Comment by Cyclenerd** [comment]
Please see: https://github.com/Cyclenerd/ethereum_nvidia_miner/issues/4
You can reduce the partition to 8 GB.

**Comment by jimmykl** [comment]
Hi @Cyclenerd Could I you please point me to a guide of how to reduce the size of a partition on on img? I tried gparted but it shows a single 28.16GB partition and won't let me reduce it's size.

**Comment by jimmykl** [comment]
![ubuntu_64-bit](https://user-images.githubusercontent.com/113574/27535544-6e55ae3a-5abf-11e7-9eee-181faa10ad7d.jpg)

**Comment by Cyclenerd** [comment]
Please Google: resize partition iso
