### ISSUE TITLE
Overclock instability?

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#19]
So I was able to recover my hashrate from a Win10 rig of 150~ by overclocking the mem by +1200 for my GTX 1060 6GBs.

However, after 20 mins of usage, this goes to 90~ hashrate, whereas under the same settings my Win10 rig is sitting happily at 150~ for over 24 hours.

x7 GPU
Win10 = 70% power consumption, 80% fan, +600 mem, -150 core
Ubuntu = 85 watt consumption, 80% fan, +1200 mem, -150 core

Is there something I'm missing here? Should the core also be -300 because of the Linux issues/translations?

**Comment by michaelphenderson** [comment]
I'm stable at +150 core & +1100 mem (using nvidia-settings in ubuntu 16.04)
Here's what it's showing me...

name, power.draw [W], fan.speed [%], temperature.gpu, clocks.current.video [MHz], clo
cks.current.memory [MHz]
GeForce GTX 1070, 111.30 W, 75 %, 60, 1670 MHz, 4353 MHz
GeForce GTX 1070, 110.68 W, 75 %, 57, 1582 MHz, 4353 MHz
GeForce GTX 1070, 109.60 W, 75 %, 60, 1645 MHz, 4353 MHz
GeForce GTX 1070, 109.24 W, 75 %, 56, 1518 MHz, 4353 MHz
GeForce GTX 1070, 84.76 W, 75 %, 51, 1670 MHz, 4353 MHz
GeForce GTX 1070, 111.58 W, 75 %, 53, 1582 MHz, 4353 MHz

each hashing 29.x not great, but stable.  I'll take it for now.  Need a few days of consistency.

**Comment by Kainzo** [comment]
Hmm, but you're also pushing 1070s, thinking thats the difference here.  If you drop core, wont you drop wattage usage?

**Comment by michaelphenderson** [comment]
Oh sorry didn't see that ignore me.

**Comment by Cyclenerd** [comment]
Again... Also in your other issue reports, several users have reported similar values with Linux. If you miner works I see no error in the USB flash driver image. I therefore close this issue too. This is not a forum. Btw. I'm I get stable 23MH/s @70W with my GTX 1060. I do not use Claymore.

**Comment by Kainzo** [comment]
@Cyclenerd that's understandable, maybe its best to have a FAQ section?
