### ISSUE TITLE
Fan speed setting

### ISSUE THREAD

**Issue by nanagnos** [Cyclenerd/ethereum_nvidia_miner#2]
Fan speeds did not change with the default script.  (could be my setup with 6  1070s)  I changed "gpu" to "fan" in the nvidia-overclock.sh file and it works fine now.
"[fan:$MY_DEVICE]/GPUTargetFanSpeed=80"

Not sure if this matters, but I am also changing GPUFanControlState to 1

"[gpu:$MY_DEVICE]/GPUFanControlState=1"

**Comment by Cyclenerd** [comment]
fixed with https://github.com/Cyclenerd/ethereum_nvidia_miner/commit/35f4b30d183c06f7598abe53e94c977a846ee832
