### ISSUE TITLE
Enhancement: Auto taskiller/restarter for stuck processes

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#20]
Is it possible to add a watch-dog task script to auto-kill stuck processes and restart them?

I've noticed on 3 occasions today that my miners just stopped responding in their genoil screen, this might be a genoil thing but was wondernig if there's anything we can do on the ubuntu to side to restart stuck screens or any system checker to provide this.

On the Minecraft server hosting side we had a pretty simple script to monitor for this and reboot if its stopped.
```

#!/bin/sh 
java \
        -Xms4G \
        -Xmx4G \
        -XX:+UseG1GC \
        -jar spigot-visions.jar
# /bin/sh
while true
do
java -Xms4G -Xmx4G -jar spigot-visions.jar
#pkill -f "spigot-beta" #Not really needed, just there in case of anything.
echo Its off..sleeping for 5
sleep 5
done
 

```

**Comment by h-town** [comment]
i scripted a solution for this based on nvidia-settings.  let me know if you're interested in the contribution.

**Comment by Cyclenerd** [comment]
I close this issue. Please pay attention to FAQ.
