### ISSUE TITLE
overclocking only works on 2 cards

### ISSUE THREAD

**Issue by azzba** [Cyclenerd/ethereum_nvidia_miner#22]
I have 6x 1060's in the rig. 

I go to run the overclock script and the first 2 are set, but the other 4 powermizer is set but nothing else is.

This leads me to believe X is not running on the other 4 cards?  best way to fix?

**Comment by Cyclenerd** [comment]
Did you follow the instructions? Have you read the FAQ? Please describe what you have done.

**Comment by azzba** [comment]
I made the image to the USB drive, booted up, changed the mine.sh to claymores dual miner, ran nvidia-config.sh, rebooted. edited the nvidia-overclock.sh and ran it.  Although for some reason reboot does not work, system will not fully turn off.  Have to keep powering it off manually.  I also switched out a bad card after first booting it up but before running nvidia-config.sh.

**Comment by Cyclenerd** [comment]
Try with 4 card. Then increase the number. Try something... And see if on any graphics card an X server is running. Error message also helps surely.

**Comment by azzba** [comment]
Ok seems to be working now.  No idea what it was, but I ran nvidia-config again and rebooted and it was working.  Sorry for the false alarm.

Also there were no error messages, just blank lines when it did happen.
