### ISSUE TITLE
ethminer not found

### ISSUE THREAD

**Issue by akha666** [Cyclenerd/ethereum_nvidia_miner#25]
Start to run miner I got "No such file or directory"
```
prospector@mine ~ $ ./miner.sh 
Persistence mode is already Enabled for GPU 0000:01:00.0.
All done.
Power limit for GPU 0000:01:00.0 was set to 120.00 W from 120.00 W.
All done.

./miner.sh: line 29: /home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer: No such file or directory
prospector@mine ~ $ 
```

**Comment by Cyclenerd** [comment]
Did you build it?

**Comment by Cyclenerd** [comment]
I close the issue. Version 2 is online.

**Comment by deftOfCenter** [comment]
@Cyclenerd I think you may have moved the ethminer directory in v2.  I also was unable to git pull from master to update.  Did you use a different branch?

(BTW, totally love the work here.  It is awesome)

**Comment by Cyclenerd** [comment]
https://github.com/ethereum-mining/ethminer is the new default.
