### ISSUE TITLE
Mining with Asrock H81 Pro BTC R2.0

### ISSUE THREAD

**Issue by bartocc** [Cyclenerd/ethereum_nvidia_miner#27]
Hi,

Feels like my motherboard is not on my network. Here's what I've done so far:

- setup my USB flash drive using `dd` (from OS X Sierra)
- plugged it on my asrock h81 pro btc 2.0 motherboard
- plugged my [ASUS GTX 1060 3Go](https://www.asus.com/fr/Graphics-Cards/DUAL-GTX1060-3G/) on the PCIe 16x connector on the motherboard (don't have my risers yet)
- plugged the ethernet cable on the motherboard
- started the motherboard

But my network tool does not report any new connected computer ...

Any idea on what's missing?

I wonder if it has to do with the "Setup - Mainboard" part of the readme:
Mainboard

```
Set the primary graphics output to on one of your NVIDIA cards. Disable Secure Boot (UEFI) and boot from the USB flash drive.
```

**Comment by Cyclenerd** [comment]
Sounds like everything is right. You can observe the boot process on the monitor? After the boot  process you can press <kbd>Crtl</kbd> + <kbd>Alt</kbd> + <kbd>1</kbd> to get a console.

**Comment by bartocc** [comment]
I've plugged the hdmi output of the GC to my TV and powering up the board takes me to the asrock screen prompting me to press F2 to enter a menu.

I did not have a keyboard with me at that moment so I'll try to see where F2 takes me.

Should I also try F12 to force the board to boot from the USB ?

I've also got an empty SSD connected to the MoBo. Maybe I should disconnect it since the USB should be enough ...

**Comment by Cyclenerd** [comment]
If you start the operating system from the USB stick, of course nothing happens. You have to adjust the settings in the BIOS. Can be that your Mainboard does not want to boot from the USB flash drive because UEFI is still on.

**Comment by bartocc** [comment]
Ok, I managed to get to the console !
Looks like the last thing I need is an internet connection. The ethernet cable is plugged but `ifconfig` does not show me my local ip ... I do see my MAC address.

Pluggin the ethernet cable on another computer works though ...

Any idea ?
Thx

**Comment by Cyclenerd** [comment]
reboot with cable.

**Comment by bartocc** [comment]
no luck ... the lights on the ethernet female are not even "orange" as usually when a cable is plugged ...

**Comment by bartocc** [comment]
this might have to do with https://askubuntu.com/questions/767786/changing-network-interfaces-name-ubuntu-16-04

**Comment by Cyclenerd** [comment]
The LED is normal on even when no operating system is started. I think you have another problem.

**Comment by bartocc** [comment]
`ifconfig` outputs a network interface named ''enp3s0"
but /etc/network/interfaces lists "enp0s31f6"

I've tried to change /etc/network/interfaces to enp3s0 but when I do so, the boot process fails with

`/sbin/ifup: waiting for lock on /run/network/ifstate.enp3s0`

Does this give you a clue as to what might be wrong?

**Comment by bartocc** [comment]
After some research, I think that my problem is that ubuntu lacks the ethernet driver for the [asrock H81 pro btc 2.0](http://www.asrock.com/mb/Intel/H81%20Pro%20BTC%20R2.0/) card: Realtek RTL8111GR.

Looks like one way out of this is to [install the 'r8168-dkms' package](https://unixblogger.com/2016/08/11/how-to-get-your-realtek-rtl8111rtl8168-working-updated-guide/), but since I have no network connection with my asrock MoBo setup, I was planning on booting from USB and downloading the package with `aptitude download r8168-dkms` from another computer and then `apt-get install /path/to/r8168-dkms` from the asrock.

I tried to boot from the USB on my mac and some other PCs, but got stuck with a `Failed to start Light Display Manager` error message during the boot process. I guess this might have to do with the fact that those machines do not have NVidia cards...

At the moment, that's how far I could go with my investigations and as long as I cannot boot from the USB from another computer, I am out of ideas.

**Comment by bartocc** [comment]
Do you think I could modify the .img you provided and flash the USB with this modified version ?

Or maybe you could install this package in your .img ...

So far, I am only *guessing* this is the culprit of my network connection not working ...

**Comment by Cyclenerd** [comment]
Just working on version 2. I have added `r8168-dkms`. I'll let you know when I'm done.

**Comment by bartocc** [comment]
I've found a PC with a NVidia card. The network connection on this PC worked fine and I could `aptitude download r8168-dkms`!

I then went back to my asrock board, booted from the USB and `sudo dpkg -i r8168-dkms .deb`.

Rebooted, and my board was finally connected to the net ! ;-)

I need to see now if it is mining, but I am making a lot of progress ;-)

**Comment by bartocc** [comment]
Installing `r8168-dkms` in the ISO you provide might not be good though, because I believe it needs to be build from the MoBo it will work on.

A solution would be to place the .deb package in your ISO and add a step in the README

**Comment by Cyclenerd** [comment]
That should not be a problem. I have understood that it is a kernel module which is not open source and thus is not in the Ubuntu standard installation. If the module is included, it will be loaded on demand.

**Comment by bartocc** [comment]
I've been mining since 2PM with my one and only 1060 for the moment.

Current effective hashrate ranges from 14.5 to 25.5, while the Average effective hashrate is about 15 at the moment

![Uploading Capture d'écran 2017-07-06 21.48.06.png…]()

Have you noticed such variations of the 'Current effective hashrate' with your cards @Cyclenerd ?

I'll see tomorrow morning if things have stabilized

**Comment by Cyclenerd** [comment]
Version 2 is online.

Look at the output of `ethminer`. You should have with one 1060 at least 20MH/s.

**Comment by bartocc** [comment]
Excellent, thx. I'll flash another USB next week with the V2 and let you know how things work !

For the moment, after overclocking mostly the memory Mhz, ethminer reports 20 to 26Mh/s with my 1060.

<img width="586" alt="capture d ecran 2017-07-07 14 35 09" src="https://user-images.githubusercontent.com/47953/27958038-80b62810-6321-11e7-83b6-7cf21a84e32c.png">

One thing I was wondering is that clocks.current.memory is 4551Mhz (I've set MY_MEM="1500" in nvidia-overclock.sh)

<img width="815" alt="capture d ecran 2017-07-07 14 34 53" src="https://user-images.githubusercontent.com/47953/27958042-869143f0-6321-11e7-833b-b532f7b30ed5.png">

but my [card's spec](https://www.asus.com/fr/Graphics-Cards/DUAL-GTX1060-3G/specifications/) says 8008Mhz.

<img width="378" alt="capture d ecran 2017-07-07 14 32 52" src="https://user-images.githubusercontent.com/47953/27957977-3bd3ec0a-6321-11e7-9562-aa1e655744a4.png">

I've tried MY_MEM="2000" which seems to be the max possible value accepted by `nvidia-settings` but even with that, I cannot come close to 8000Mhz.

Do you believe reaching 8000Mhz is advisable and/or doable ?

**Comment by bartocc** [comment]
@Cyclenerd I'd like to PM you. What's your preferred way for that ?

Thx

**Comment by jimmykl** [comment]
@bartocc Re: overclock speeds

It's a bit confusing but you need to multiply the setting used in most overclocking tools by 4 to get the equivalent reading as listed on the card's spec. The manufacturers obviously use the larger number because bigger = better for marketing.

The reason is GDDR5 memory uses quad data rate speeds which work at 4x the actual memory speed. So 2002 would be the maximum setting for your card. If you try setting 8000 you'd be asking the memory to work at 32,000MHz!

This explains it quite weel: http://www.geeks3d.com/20100613/tutorial-gpu-tools-and-gpu-memory-clock-real-and-effective-speeds-demystified/

**Comment by Cyclenerd** [comment]
Works with the new image with the Asrock H81 Pro BTC R2.0?

**Comment by bartocc** [comment]
I'll test next week. I'm not close to my rig this we

**Comment by bartocc** [comment]
Just tried V2 and the network issues I had with V1 are gone !

The network card got an IP from DHCP as soon as I plugged the ethernet cable and I've been able to ssh into Ubuntu right away.

Thx
