### ISSUE TITLE
Overclocking?

### ISSUE THREAD

**Issue by b0gd4n** [Cyclenerd/ethereum_nvidia_miner#29]
Hey there,

First off, I know you don't want discussions here, but I think this is more of a troubleshooting post.

I have a 980ti running on water and am trying to run the `nvidia_overclock` script. Thing is, even if I set the clock and memory offsets to 0, I am getting this:

```
Attribute 'GPUPowerMizerMode' (mine:0[gpu:0]) assigned value 1.

Attribute 'GPUFanControlState' (mine:0[gpu:0]) assigned value 1.

Attribute 'GPUTargetFanSpeed' (mine:0[fan:0]) assigned value 80.


ERROR: Error assigning value 0 to attribute 'GPUGraphicsClockOffset' (mine:0[gpu:0]) as specified in assignment
       '[gpu:0]/GPUGraphicsClockOffset[3]=0' (Unknown Error).


ERROR: Error assigning value 0 to attribute 'GPUMemoryTransferRateOffset' (mine:0[gpu:0]) as specified in assignment
       '[gpu:0]/GPUMemoryTransferRateOffset[3]=0' (Unknown Error).

Done
```

On another note, when running `mine`, I am getting this:

```
prospector@mine:~ $ mine
 00:31:02 up 16 min,  3 users,  load average: 0.53, 0.31, 0.37
==> Please wait 1 minute!
There is no screen to be detached.
```

No matter how long I wait, I always get this.

EDIT: I realised the last issue (about running `mine`) happens after I hit `Ctrl+C`. My question is, how do I get the mining task up and running back up without restarting?

**Comment by b0gd4n** [comment]
Upon further testing, I found that, even if I always get the errors above, setting the clock speed actually works. However, the memory speed never changes.

**Comment by b0gd4n** [comment]
I just tried `nvidia-smi` and it seems to work on mine (as long as I sudo it)

**Comment by Cyclenerd** [comment]
I have also read in forums that the Ti models can be overclocked with `nvidia-smi`. To your other question: `newmine` creates a new `screen`
