### ISSUE TITLE
No setup program

### ISSUE THREAD

**Issue by baydosw** [Cyclenerd/ethereum_nvidia_miner#30]
Hello,

There doesn't seem to be a setup program available. When I login and type setup I get an error. I have the default video pointed to one of my cards. I am in fine via ssh. I have reflashed my USB multiple times.

**Comment by Cyclenerd** [comment]
Please post the output from the command `ls -lah ~`.

**Comment by baydosw** [comment]
prospector@mine ~ $ ls -lah
total 192K
drwxr-xr-x 24 prospector prospector 4.0K Jul  8 21:05 .
drwxr-xr-x  3 root       root       4.0K Jun 17 19:06 ..
-rw-------  1 prospector prospector   45 Jun 24 09:21 .bash_history
-rw-r--r--  1 prospector prospector  220 Jun 17 17:32 .bash_logout
-rw-r--r--  1 prospector prospector 4.6K Jun 24 09:06 .bashrc
-rw-r--r--  1 prospector prospector 3.7K Jun 17 19:05 .bashrc.ORIG
drwx------  9 prospector prospector 4.0K Jun 22 14:56 .cache
drwxrwxr-x  2 prospector prospector 4.0K Jun 22 16:26 claymore-dual-miner
drwx------ 16 prospector prospector 4.0K Jun 22 10:01 .config
drwxrwxr-x 15 prospector prospector 4.0K Jun 17 20:24 cpp-ethereum
drwx------  3 prospector prospector 4.0K Jun 22 08:44 .dbus
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 09:13 Desktop
-rw-r--r--  1 prospector prospector   23 Jun 22 08:44 .dmrc
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Documents
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Downloads
drwx------  2 prospector prospector 4.0K Jun 22 09:13 .gconf
-rw-rw-r--  1 prospector prospector  224 Jun 17 19:05 .gitconfig
drwxr-xr-x  3 prospector prospector 4.0K Jun 22 08:26 .local
drwx------  2 prospector prospector 4.0K Jun 22 17:10 Mail
-rwxrwxr-x  1 prospector prospector 1.1K Jun 24 09:06 miner.sh
drwx------  4 prospector prospector 4.0K Jun 22 09:13 .mozilla
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Music
-rwxrwxr-x  1 prospector prospector   94 Jun 22 21:30 myip.sh
drwxrwxr-x  2 prospector prospector 4.0K Jun 17 19:35 .nano
-rw-rw-r--  1 prospector prospector   86 Jun 17 19:05 .nanorc
drwx------  4 prospector prospector 4.0K Jun 22 09:32 .nv
-rwxrwxr-x  1 prospector prospector  303 Jun 24 09:07 nvidia-config.sh
-rwxrwxr-x  1 prospector prospector  915 Jun 24 09:07 nvidia-overclock.sh
-rw-rw-r--  1 prospector prospector 3.0K Jun 22 18:54 .nvidia-settings-rc
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:53 Pictures
-rw-r--r--  1 prospector prospector  874 Jun 17 19:05 .profile
-rw-r--r--  1 prospector prospector  655 Jun 17 19:05 .profile.ORIG
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Public
-rw-rw-r--  1 prospector prospector 1.2K Jun 24 09:06 .screenrc
drwxrwxr-x  2 prospector prospector 4.0K Jun 17 19:05 Scripts
drwx------  2 prospector prospector 4.0K Jun 23 19:02 .ssh
-rw-r--r--  1 prospector prospector    0 Jun 17 18:17 .sudo_as_admin_successful
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Templates
-rw-rw-r--  1 prospector prospector 1.6K Jun 17 19:05 .tmux.conf
-rwxrwxr-x  1 prospector prospector  962 Jun 24 09:08 update.sh
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 08:44 Videos
-rw-------  1 prospector prospector  745 Jun 22 21:30 .viminfo
drwxr-xr-x  2 prospector prospector 4.0K Jun 22 15:10 .vnc
-rw-------  1 prospector prospector  294 Jul  8 21:05 .Xauthority
-rw-rw-r--  1 prospector prospector 8.0K Jun 22 09:08 .xscreensaver
-rw-------  1 prospector prospector  245 Jul  8 21:05 .xsession-errors
-rw-------  1 prospector prospector  245 Jun 24 09:18 .xsession-errors.old
prospector@mine ~ $ setup
setup: command not found
prospector@mine ~ $ setupcon
We are not on the console, the console is left unconfigured.
prospector@mine ~ $

**Comment by Cyclenerd** [comment]
You are not using version 2!

**Comment by baydosw** [comment]
Ah. Will do. Thanks for the quick response!
