### ISSUE TITLE
Beginner Setup Issues

### ISSUE THREAD

**Issue by mgcox** [Cyclenerd/ethereum_nvidia_miner#31]
I installed and ran v2 as a first time user and had issues. I am willing to create have more clear setup instructions once I am able to get things working because some of the setup parts were a little unclear. 

In the setup:

8: Configure graphics cards. (personally using 6 gtx 1070's)
If there could be some recommended value or range, it would help users who have no idea what their power limit, clock offset, transfer rate offset, and fan set should be. 
If there were default settings for these... or some clear answers on how to find the values to use, that would be helpful

Once setup is complete and the device is rebooted, will it automatically start running after 60 seconds? How can we verify that it is running? If we can verify by running `crontab -l`  then what should we be looking for when it lists the cron tasks

when running the command "mine" what if no data shows up? Or what are the numbers we are seeing on the screed? 

I am willing to submit a pull request with this information clearly marked if I can get some explanations for these enough to get v2 running.

ssh issue: I have looked EVERYWHERE online for this issue and wanted to see someone else had this problem too. 

x$ ssh -vvv prospector@10.0.0.32 
OpenSSH_7.4p1, LibreSSL 2.5.0
debug2: resolving "10.0.0.32" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.0.0.32 [10.0.0.32] port 22.
debug1: Connection established.
debug1: identity file /Users/x/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/x/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.0.0.32:22 as 'prospector'
debug3: hostkeys_foreach: reading file "/Users/z/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Connection closed by 10.0.0.32 port 22

**Comment by mgcox** [comment]
I was able to fix the ssh issue with:
sudo apt-get purge openssh-server
sudo apt-get install openssh-server

**Comment by Cyclenerd** [comment]
The internet is fully recommended with every graphics card type. Everyone takes a different risk. I do not make any recommendations. With the standard, everything should be doing well.

What is a concrete question. What did you not understand?

> Once setup is complete and the device is rebooted, will it automatically start running after 60 seconds?

Yes: https://github.com/Cyclenerd/ethereum_nvidia_miner#mine

> After a minute uptime, a script (screen) starts automatically in the background, which starts the mining.

https://github.com/Cyclenerd/ethereum_nvidia_miner#minersh

> The miner.sh script starts automatically (mine console). If you want to make settings that go beyond the setup program, you need to adjust it.

For your SSH problem. Did you get a mail from root with errors from first_boot.sh script?

**Comment by mgcox** [comment]
This issue can be closed. 

I will make a push request if I feel a need to improve the documentation.
