### ISSUE TITLE
Change Hostname to Name of Rig

### ISSUE THREAD

**Issue by keithkk** [Cyclenerd/ethereum_nvidia_miner#32]
The hostname is pre-defined to a value of mine and loaded at boot. It does not update or change when the name of the rig is changed. It would be better if these values were dynamic so that their values match the user defined value in the Name Your Rig field. With multiple mining rigs named, for example, miner01, miner02, miner03, etc., not having to update the hostname value multiple times directly in Ubuntu and Setup for each rig would be more efficient.

Thank you very much for sharing a great tool and for all the work put into it. Much appreciated!!!

**Comment by Cyclenerd** [comment]
I close this issue, because it is not a issue. I see no advantage in a different host name. As you write yourself the hostname can easily be changed in the `/etc/hostname` and `/etc/hosts`. Should also be set via DHCP: https://tools.ietf.org/html/rfc1533#section-3.14

**Comment by h-town** [comment]
this isn't an "issue" per-se and changing hostnames is quite easy (as you point out), but you might consider it a feature request.  managing multiple rigs would be easier with disparate hostnames, and would make networking them easier.  it can obviously be done via external networking equipment as well, but having the machine know its assigned host would be "nice to have"
