### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by stsvilik** [Cyclenerd/ethereum_nvidia_miner#33]
I ran into issues while attempting to update ethminer. Keyboard mapping is off for me and I had issues finding ```_``` key which somehow is mapped to ```?``` key instead of normal "underscore/dash" key. Similar issues for "dash" which is mapped to a "minus" on NumPad only.

**Comment by jimmykl** [comment]
@Cyclenerd will have it set to German. Try ```sudo dpkg-reconfigure keyboard-configuration```

**Comment by stsvilik** [comment]
@jimmykl I'll try that, ty!

**Comment by Cyclenerd** [comment]
Keyboard layout can be changed with setup. Point 9. Is not really needed. SSH does not matter.

**Comment by h-town** [comment]
you realize that you need to type a forward slash to begin setup in the first place, correct?  either $full path or ./setup.sh...but a forward slash is necessary either way.  i too had to use dpkg-reconfigure keyboard-configuration back when i set it up.

**Comment by Cyclenerd** [comment]
As described in the manual, you must enter `setup`. No dot no slash.

**Comment by h-town** [comment]
for those of us who took our linux training wheels off some time ago (read: immediately ls when we login) the setup.sh file in ~/home leads one to believe it isn't aliased. ;)

you might consider dropping a quick login script that runs keyboard configuration if setup.sh has never been touched.  here again, just a suggestion for improvement.

**Comment by stsvilik** [comment]
To reinforce the need for correct keyboard layout - the only time I needed it is when I had trouble with "Dummy Monitors" and wanted to revert (thus needed to navigate through bash)
