### ISSUE TITLE
Invalid refresh rate when switching to screen from Dummy Monitor

### ISSUE THREAD

**Issue by stsvilik** [Cyclenerd/ethereum_nvidia_miner#34]
As instructed I have configured my rig to be "headless" but when I tried to access it using ```CTRL + ALT + F1``` (I think) to re-enter screen, my monitor complained about incompatible refresh rate and failed to display anything. My monitor is older version of Dell Ultra  23" and usually supports wide range of resolutions, so I'm not sure what happened there.

P.S. Please mention the shortcut to re-enter "screen" mode from "headless" in the readme. The only time it is ever mentioned is in the setup.

**Comment by Cyclenerd** [comment]
This is also in the FAQ:
https://github.com/Cyclenerd/ethereum_nvidia_miner/blob/master/FAQ.md#my-connected-monitor-stays-black-why

Can you observe the boot process? Grub selection, etc... Why do you need the monitor when you write yourself that you have configured everything for headless?

**Comment by stsvilik** [comment]
I had difficulty SSH into the box, so I decided to see whats going on through the monitor.

Thanks for FAQ link - perhaps it should be referenced/mentioned near the part about turning your box headless :)

**Comment by Cyclenerd** [comment]
Please answer the other questions... Or could you solve it in the meantime?

**Comment by stsvilik** [comment]
Sorry - yes, I was able to observe boot process up until login, then it turned off monitor.

**Comment by Cyclenerd** [comment]
This is normal. This is also described in the `setup` and in the manual.

If you can see the boot process, you should also be able to switch to the console. Both have the same refresh rate. 

If not then:

* You do something wrong with the key combination.
* Your X server brings the computer to crash.
    * This can be if you have not disabled the internal card. Follow the instructions.
    * Try to connect via SSH. In delete the xconf.
* Your monitor is "confused".
