### ISSUE TITLE
[V1] Get performance state P0 instead of P2

### ISSUE THREAD

**Issue by bartocc** [Cyclenerd/ethereum_nvidia_miner#35]
*Disclaimer: I am still using V1 at the moment (I should be able to test v2 tomorrow). I will see then if things are different.*

`nvidia-smi` reports that my GPU performance state is P2, while nvidia-overclock.sh should set it to P0 with that line `nvidia-settings -a "[gpu:$MY_DEVICE]/GPUPowerMizerMode=1"`

Any idea why?

**Comment by asinatra** [comment]
This is not an issue with ethereum_nvidia_miner.

P states for a very large majority of GTX 10 do not currently work as they did for GTX 9 in both linux and windows platforms.

`nvidia-smi –q –d SUPPORTED_CLOCKS`

If that returns N/A then you cannot set the P state with GPUPowerMizerMode or nvidia-smi -ac

Your overclock offsets will be higher, that is all.

**Comment by Cyclenerd** [comment]
Super explained by @asinatra 👍 
I close this issue.

**Comment by bartocc** [comment]
Thx @asinatra for the great explanation!
