### ISSUE TITLE
Dual mining doubt

### ISSUE THREAD

**Issue by Gustav0ar** [Cyclenerd/ethereum_nvidia_miner#37]
First, thanks for the image, helped me a lot with my rig. Very easy to use.
Is it possible to dual mining with your setup? If so, any advice on how should I do it?
Is there performance loss when doing?

My machine got 4x Nvidia 1070. Waiting for another 2 to arrive...

Thanks

**Comment by Cyclenerd** [comment]
That's fine. But this is the wrong place for discusion.
