### ISSUE TITLE
Adjust fan speed based on temperature

### ISSUE THREAD

**Issue by andreasd** [Cyclenerd/ethereum_nvidia_miner#38]
I made a small script that would get rid of the $MY_FAN variable. It reads the current GPU temperature (of each GPU individually) and sets the fan speed according to it (e.g. 40°C --> 40%, 65°C --> 90%, >70°C --> 100% - these are not the exact numbers, just to give you an idea). The temperature is checked every minute and this works pretty well (was not expecting that such a simple control works and was already thinking on how to implement a PID ;) ). 

this works better for me than a static fan speed, as my rigs get some sun in the morning and need higher speeds there, but at night they run pretty cool and are fine with 50% fanspeed (makes them also less noisy).

would you be interested in this? I could clean it up and make a pull request.

**Comment by h-town** [comment]
i did the same thing for GPU utilization.  system reboots any CPU drops below 80%.  made the same offer you did but was slapped in the hand for "using issues thread as a forum" or something of the like.  granted, i'm not keen on this github pull request action.

**Comment by Cyclenerd** [comment]
The graphics card (driver) can control the speed of the fan itself if the value does not set.

**Comment by andreasd** [comment]
yes, but it will let the gpus heat up quite high (up to 80°C) which is okay in normal use cases where you don't run a system 24/7 (or if you're fine with gpu throttling). that's the reason why you even set a fanspeed to begin with...

**Comment by Cyclenerd** [comment]
Right! Good reason. You're welcome to send a pull. Please note: do not forget `setup` and the setting must be super simple. If not, there are many questions.

I make close this issue. There is nothing broken.
