### ISSUE TITLE
read GPU numbers from lspci

### ISSUE THREAD

**Issue by andreasd** [Cyclenerd/ethereum_nvidia_miner#39]
gpu numbers are currently hard coded in the scripts. they could easily be determined with a few lines like this:

```
GPUS=`lspci -vnn | grep VGA | grep NVIDIA | wc -l`
GPUS=`expr $GPUS - 1`
```

which then can be used in the scripts (like nvidia-overlock.sh):

`for MY_DEVICE in $(eval echo "{0..$GPUS}")`

**Comment by Cyclenerd** [comment]
But there is a problem: `lspci` can show more graphics cards than drivers loaded. `nvidia-smi --list-gpus` would be better. But I think it does not improve anything to determine the number of graphics cards.

**Comment by andreasd** [comment]
you would get rid of the hard coded 5 in the scripts. the scripts won't work sufficient if you use 8 gpus and will produce errors if you have less.

**Comment by Cyclenerd** [comment]
Are you successfully running a rig with more than six graphics cards?

**Comment by h-town** [comment]
7 cards here; all nvidia.  i've seen videos & forum posts of up to 12 on a single mobo.  all that to be said, it's doable.

**Comment by Cyclenerd** [comment]
@h-town Please send me a pull to remove this https://github.com/Cyclenerd/ethereum_nvidia_miner#known-issues. This has been added by another user. In the pull please describe your setup (exact hardware details). I am poor and have only 5 graphics cards and enough problems with it ;-)

**Comment by asinatra** [comment]
Only those with a single gpu or gpus of all the same model should be blanket tuning.

```
nvidia-oc 0 max 90 992 260
nvidia-oc 1 max 80 500 50
nvidia-oc 2 max 90 992 260
nvidia-oc 3 max 80 600 0
nvidia-oc 4 max 75 800 150
```

```
#!/usr/bin/env bash
if [ "$#" -ne 5 ]; then

        echo "nvidia-oc [index] [power limit] [fan speed] [memory offset] [graphics offset]"
else

        # nvidia-smi
        # power limit
        if [ "${2}" == "max" ]; then
                GPU_INDEX="$(expr $1 + 1)"
                POWER_LIMIT="$(nvidia-smi --query-gpu=power.max_limit --format=csv,noheader | sed -n ${GPU_INDEX}p | sed 's|[ W,]||g')"
                sudo nvidia-smi -i "$1" -pl "$POWER_LIMIT"
        else
                sudo nvidia-smi -i "$1" -pl "$2"
        fi

        # nvidia-settings
        export DISPLAY=:0

        # fan speed
        nvidia-settings -a "[gpu:$1]/GPUFanControlState=1"
        nvidia-settings -a "[fan:$1]/GPUTargetFanSpeed=$3"

        # memory clock
        nvidia-settings -a "[gpu:$1]/GPUMemoryTransferRateOffset[3]=$4"

        # graphics clock
        nvidia-settings -a "[gpu:$1]/GPUGraphicsClockOffset[3]=$5"

fi
```

**Comment by Cyclenerd** [comment]
@asinatra expr is antiquated. Consider rewriting this using $((..)), ${} or [[ ]]. Double quote everything to prevent globbing and word splitting. Super also would be: If no values(parameter) is set, take value from the settings.conf.Add exit codes. Add some more documentation and then send a pull. A cool name for your script would be. `ococ.sh` OverClock One Card :-)

Also consider if `getopts` would be better. A good example for copy & paste can be found here:
https://github.com/Cyclenerd/toolbox/blob/master/bitcoin/btc_rates.sh

**Comment by asinatra** [comment]
@Cyclenerd I am still on your original version, the new setup.sh has deterred me using v2 as it lost the KISS.
