### ISSUE TITLE
16gb usb?

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#4]
I'm starting to install this but im using a 16GB USB is this going to be an issue?

**Comment by Cyclenerd** [comment]
It will not work. Please follow the instructions. At least 32GB.

**Comment by Kainzo** [comment]
Hey Cyclenerd... what are the reasonings for 32GB requirement? EthOS requires 16GB

Is it because the .img file in the torrent is using a raw copy of a 32GB drive?  I'm running to get a 32GB USB now... Do you have instructions on getting it on a 60GB SSD?

**Comment by Cyclenerd** [comment]
I had just a 32GB stick. The cost is not much more than 16GB. The image and partition is therefore 32GB. If you reduce the partition it also fits on 8GB stick.

**Comment by Cyclenerd** [comment]
Btw. most 32GB USB 3.0 sticks are faster than 16GB.

**Comment by Kainzo** [comment]
Thank you.  I've installed this now, so ill be posting more :) appreciate it!
