### ISSUE TITLE
nvidia-overclock or nvidia-smi doesn't work on VGA mining

### ISSUE THREAD

**Issue by maximum733** [Cyclenerd/ethereum_nvidia_miner#43]
Hi there, i have a rig using P106-100 mining. im using claymore for mine and its run correctly but i can't using overclock feature. anyone having same my issue?

**Comment by Cyclenerd** [comment]
Error message? What have you done so far? More details.

**Comment by maximum733** [comment]
ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
specified in assignment '[gpu:{0..5}]/GPUPowerMizerMode=1'.

ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
specified in assignment '[gpu:{0..5}]/GPUFanControlState=1'.

ERROR: Error resolving target specification 'fan:{0..5}' (No targets match target specification),
specified in assignment '[fan:{0..5}]/GPUTargetFanSpeed=75'.

ERROR: Error parsing assignment '[gpu:{0..5}]/GPUGraphicsClockOffset[3]==100' (No attribute value
specified).

ERROR: Error resolving target specification 'gpu:{0..5}' (No targets match target specification),
specified in assignment '[gpu:{0..5}]/GPUMemoryTransferRateOffset[3]=600'.


this error appear when i trying to run command
`prospector@mine ~ $ nvidia-overclock`
im following step by step in README.md

**Comment by Cyclenerd** [comment]
Dit you really enter `nvidia-overclock`? The error message indicates wrong input, like `sh nvidia-overclock.sh`.

**Comment by maximum733** [comment]
i just write this in terminal: `nvidia-overclock`

**Comment by Cyclenerd** [comment]
Just to be sure: write `bash nvidia-overclock.sh`

**Comment by h-town** [comment]
if that doesn't work, paste the output of nvidia-smi here.  it's possible
(albeit unlikely) that your gpu bus IDs don't match those specified in the
script.

**Comment by maximum733** [comment]
ok i will try and tell you guys the result here.

**Comment by maximum733** [comment]
Well. I was trying to use command “bash nvidia-overclock.sh” and i got this message:

Attribute ‘GPUPowerMinerMode’ (mine:0[gpu:0]) assigned value 1.

ERROR: Error assigning value 0 to attribute ‘GPUTargetFanSpeed’ (mine:0[fan:0]) as specified in assignment ‘[fan:0]/GPUTargetFanSpeed=0’ (Unknown Error).

Done

**Comment by r33net** [comment]
Run "bash nvidia-config.sh" und reboot your system.  run "bash nvidia-overclock.sh" again

**Comment by maximum733** [comment]
I've tried do exactly your guide @r33net. But error still appear same before

**Comment by r33net** [comment]
I had the same error and could fix this.

**Comment by Cyclenerd** [comment]
Here all have the same card as the OP - Asus P106-100? If not, it would certainly help to post the graphics card model. Many comments simply do not make fun to read. Simply much too little details.

**Comment by Cyclenerd** [comment]
@maximum733 0 as fan speed is not a good idea. That tells you the message.

**Comment by mnik247** [comment]
I fixed this errors for new rig with "setup"-> 6-Generate Fake Monitors-> reboot

**Comment by maximum733** [comment]
@mnik247 im follow your guide and fixed my issue

**Comment by maximum733** [comment]
Problem's solved on my gtx 1060 6gb gaming x edition. Ill test on my rig with 6 P106-100 mining edition and i hope its work. Coz P106-100 cards dont have I/O port

**Comment by maximum733** [comment]
Ok i have tested with my p106-100 rig. Its work but when i tried use command “bash nvidia-overclock.sh” its dont apply memory transfer rate offset with my value “750”, same with core clock value doesnt apply. Only fan speed can be applied.

**Comment by maximum733** [comment]
Image
https://m.imgur.com/zgfnUPJ
http://imgur.com/TLZKbHL

**Comment by maximum733** [comment]
And a thing. My p106-100 just got 2.0mhs per card! Lmao... In windows it can 24mhs if increase memory to 700

**Comment by mnik247** [comment]
to @maximum733 
1) In windows mem overclock "+750" = in Linux mem overclock "+1500" (twice from windows)
2) look GPUs current setting:
2a) from screen (gpu window): mine -> CTR+a+3 
2b) direct command:  nvidia-smi --format=csv --query-gpu=name,power.draw,fan.speed,temperature.gpu,clocks.video,clocks.mem

**Comment by maximum733** [comment]
@mnik247 Oh i dont know about in linux mem clock twice from windows. Ill try but 2mhs per card is suck xD

**Comment by Cyclenerd** [comment]
I summarize:

* You did not follow the instructions. After you created this issue, you ran through the `setup`.
* Now you are talking about clock rates and other basics.
* Now you wonder why with Windows and another Miner version everything was better.
* You did not look into the FAQ.

I close this issue. Read the manual! And because all this annoying me, I close the issue function.

Again:
Read the manuel and the FAQ again!
