### ISSUE TITLE
Ctrl + n doesnt do anything in "mine"

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#5]
> Use Ctrl + n (next) and Ctrl + p (previous) to navigate through the windows (consoles).

I'm attempting this and its actually not working.  Is there another way to navigate through the screens?

**Comment by Cyclenerd** [comment]
Via SSH or directly from the keyboard to the computer?

**Comment by Cyclenerd** [comment]
Ahh. Sorry... Error in Doku CRTL + A + N

**Comment by Kainzo** [comment]
Alright, I tried "ctrl + A" and it immediately moved to the "top" screen.

Just trying to figure out the best way to do this.  Also I have tried putty and secure shell (My preferred SSH)

**Comment by Cyclenerd** [comment]
fixed https://github.com/Cyclenerd/ethereum_nvidia_miner/commit/92bf3955b0a1d520c49caee9a6537d0b949b7619
<kbd>crtl</kbd> + <kbd>a</kbd> and subsequently + <kbd>n</kbd>

**Comment by Kainzo** [comment]
Can there be a better way to do this for SEcure Shell SSH? Ctrl + n creates a new chrome screen.  Even in Putty Ctrl + N doesnt do anything.

**Comment by Cyclenerd** [comment]
subsequently! Three keystrokes not two.

**Comment by Kainzo** [comment]
10-4.

I misread that, thanks! It's working.  Oddly though, my claymore miner isnt starting the cards its just frozen.  if I cant get it to work ill start another ticket, thanks.
