### ISSUE TITLE
Miner Freezes / claymore not starting

### ISSUE THREAD

**Issue by Kainzo** [Cyclenerd/ethereum_nvidia_miner#6]
https://paste2.org/fAIaLkWe

Grabbed the latest configs, swapped addresses to claymore/wallet.  Miner doesnt start. 

It could be something on my end but im trying to figure it out from here, i was up and running before, close ticket if its not something caused by the latest update.

**Comment by Cyclenerd** [comment]
Did you adjust the powerlimit? If not, do it.

**Comment by Kainzo** [comment]
I havent adjusted anything in power, shouldnt it start hashing immediately?

**Comment by Cyclenerd** [comment]
Please `reboot` your computer. How is the output of `nvidia-smi`. There you should see all the cards. There you should see all the cards. On each, the X server must be running.

**Comment by Cyclenerd** [comment]
I close this issue. No respond. In other issue, user is talking about overclocking.
