### ISSUE TITLE
OS never reaches shell login

### ISSUE THREAD

**Issue by the2Faces** [Cyclenerd/ethereum_nvidia_miner#7]
During the bootup of the ubuntu server, the OS tries several times to startup the NVIDIA Persistance Deamon.
But this never happens, and the startup process get stuck after "Failed to start light display Manager"

No login via the delivered user is possible.

The image, which was provided via torrent, was written via Win32Diskimager on a small old ssd and an USB Key.
Neither is working.

No keystrokes are accepted. 
Only the powerbutton is able to cause a reaction of the os by proceeding with the shutdown of the system.

**Comment by the2Faces** [comment]
Okay, I was trolled by the Nvidia cards itself.

The mining machine, has an integrated amd graphicschip only for display purposes. Usually no display is attached to the other graphics cards for mining.

After I attached the monitor to the cards, I was able to work at least with the Desktop.

Interestingly, no shell access is possible, when working with the amd output.

**Comment by Cyclenerd** [comment]
That's true. You must change this in the settings of the mainboard. Doku has been updated.
https://github.com/Cyclenerd/ethereum_nvidia_miner/commit/32ee421b652e6404fcd50e63bef8f04249f0bc0b
